bots:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd /tmp
    - git clone https://gitlab.com/sugaroid/sugaroid-discord
    - cd sugaroid-discord
    - dpl --provider=heroku --app=sugaroid-discord --api-key=$SUGAROID_DISCORD_HEROKU_API_KEY
    - cd /tmp
    - git clone https://gitlab.com/sugaroid/sugaroid-telegram-python 
    - cd sugaroid-telegram-python 
    - dpl --provider=heroku --app=sugaroid-telegram --api-key=$SUGAROID_TELEGRAM_HEROKU_API_KEY
  
  only:
    - master
    - main
