[book]
authors = ["Srevin Saju"]
language = "en"
multilingual = false
src = "src"
title = "Sugaroid"
description = "Open Source, machine learning cute and friendly bot"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/srevinsaju/sugaroid"
site-url = "/sugaroid/docs/"

[preprocessor.katex]
